---
name: Stylua Check

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - nvim/**.lua
  workflow_dispatch:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Stylua
        run: |
          curl -Lo ${{ env.STYLUA_ZIP_PATH }} ${{ env.STYLUA_ZIP_URL }}
          unzip ${{ env.STYLUA_ZIP_PATH }} -d ${{ env.STYLUA_BIN_PATH }}
        env:
          STYLUA_ZIP_URL: https://github.com/JohnnyMorganz/StyLua/releases/download/v2.0.2/stylua-linux-x86_64-musl.zip  # yamllint disable-line rule:line-length
          STYLUA_ZIP_PATH: $RUNNER_TEMP/stylua.zip
          STYLUA_BIN_PATH: /usr/local/bin

      - name: Stylua Check
        run: stylua --check .
        working-directory: nvim/
